import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ResponsiveAppBar from './Components/navbar'
import DenseAppBar from './Components/navbar'
import SearchAppBar from './Components/navbar'

import Products from './Components/products'
// import MenuIcon from "@material-ui/icons/Menu";
// import { Menu as MenuIcon } from "@material-ui/icons";



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
    <ResponsiveAppBar/>

        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Products/> */}
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Next.js Tutorial 
        </h1>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}



